FROM ubuntu:22.04
RUN apt-get update
RUN apt-get install -y nginx
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends php8.1
RUN apt-get install -y php8.1-fpm php8.1-cli php8.1-mysql php8.1-curl
RUN mkdir /etc/api
COPY default.conf /etc/nginx/sites-available/api
RUN ln -s /etc/nginx/sites-available/api /etc/nginx/sites-enabled/
RUN rm /var/www/html/index.nginx-debian.html
COPY www.conf /etc/php/8.1/fpm/pool.d/www.conf
EXPOSE 80
COPY api1.php /var/www/html/api1.php
RUN chmod 775 /var/www/html/api1.php
COPY api2.php /var/www/html/api2.php
RUN chmod 775 /var/www/html/api2.php
CMD /etc/init.d/php8.1-fpm start && nginx -g 'daemon off;'