
services:
 pwsh:
  image: miketomasulo/pwsh:latest
  build: ./Container_Build/pwsh
  networks:
   - backend
  volumes:
   - pingtest_vol:/etc/pingtest_web
  environment:
   -  "TZ=America/New_York"
   -  "PT_PASS=putYourPasswordHere"
  container_name: PingTest_pwsh
  entrypoint:
   - /usr/bin/pwsh
  command:
   - /etc/pingtest/run.ps1
  dns:
   - "8.8.8.8"
  privileged: TRUE
 display:
   image: miketomasulo/display:latest
   build: ./Container_Build/display
   networks:
      - backend
   volumes:
      - pingtest_vol:/etc/pingtest_web
   environment:
      -  "TZ=America/New_York"
      -  "PT_PASS=putYourPasswordHere"
   container_name: PingTest_display
   entrypoint:
      - /usr/bin/pwsh
   command:
      - /etc/pingtest/run.ps1
   dns:
      - "8.8.8.8"
   privileged: TRUE
 mysql:
  image: miketomasulo/mysql:latest
  build: ./Container_Build/mysql
  networks:
   - backend
  volumes:
   - pingtest_vol_mysql:/var/lib/mysql
  environment:
   -  "MYSQL_ROOT_PASSWORD=StartupPassDoNotChange"
   -  "TZ=America/New_York"
  container_name: PingTest_mysql

 adminer:
    image: miketomasulo/adminer:latest
    build: ./Container_Build/adminer
    environment:
     -  "PT_PASS=putYourPasswordHere"
    networks:
     - backend
    container_name: PingTest_adminer

 chart:
    image: miketomasulo/chart:latest
    build: ./Container_Build/chart
    networks:
     - backend
    environment:
     -  "PT_PASS=putYourPasswordHere"
    container_name: PingTest_chart

 api:
    image: miketomasulo/api:latest
    build: ./Container_Build/api
    environment:
     -  "PT_PASS=putYourPasswordHere"
     -  "apikey=putYourPasswordHere"
    networks:
     - backend
    container_name: PingTest_api
 web:
  image: miketomasulo/nginx:latest
  build: ./Container_Build/nginx
  ports:
   - 80:80
   - 443:443
  networks:
   - backend
  volumes:
   - pingtest_vol:/usr/share/nginx/html
  container_name: PingTest_nginx


networks:
 backend: {}
volumes:
 pingtest_vol:
 pingtest_vol_mysql: