FROM ubuntu:22.04
RUN apt-get update
RUN apt-get install -y nginx
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends php8.1
RUN apt-get install -y php8.1-fpm php8.1-cli php8.1-mysql php8.1-curl
RUN apt-get install -y php8.1-gd
RUN mkdir /etc/chart
COPY default.conf /etc/nginx/sites-available/chart
RUN ln -s /etc/nginx/sites-available/chart /etc/nginx/sites-enabled/
RUN rm /var/www/html/index.nginx-debian.html
COPY www.conf /etc/php/8.1/fpm/pool.d/www.conf
RUN apt-get install -y unzip
EXPOSE 80
COPY Web.zip /var/www/Web.zip
RUN unzip /var/www/Web.zip -d /var/www/
CMD /etc/init.d/php8.1-fpm start && nginx -g 'daemon off;'