FROM ubuntu:22.04
COPY default.conf /etc/nginx/conf.d/default.conf
RUN apt-get update
RUN apt-get install -y nginx
RUN apt-get install -y openssl
COPY nginx.conf /etc/nginx/nginx.conf
CMD ["/usr/sbin/nginx", "-g", "daemon off;"]