FROM ubuntu:22.04
ENV VERSION_ID=22.04
RUN mkdir /etc/pingtest
COPY run.ps1 /etc/pingtest/run.ps1
COPY good.ico /etc/pingtest/good.ico
COPY bad.ico /etc/pingtest/bad.ico
RUN apt-get update
RUN apt-get install -y wget apt-transport-https software-properties-common
#RUN source /etc/os-release
RUN wget -q https://packages.microsoft.com/config/ubuntu/$VERSION_ID/packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb
RUN rm packages-microsoft-prod.deb
RUN apt-get update
RUN apt-get install -y powershell
RUN pwsh -c Set-PSRepository PSGallery -InstallationPolicy Trusted
RUN pwsh -c install-module simplysql -RequiredVersion 2.1.0.96
