FROM ubuntu:22.04
RUN apt-get update
RUN apt-get install -y nginx
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends php8.1
RUN apt-get install -y php8.1-fpm php8.1-cli php8.1-mysql php8.1-curl
RUN mkdir /etc/adminer
COPY default.conf /etc/nginx/sites-available/adminer
RUN ln -s /etc/nginx/sites-available/adminer /etc/nginx/sites-enabled/
COPY index.php /var/www/html/index.php
RUN chmod 775 /var/www/html/index.php
COPY editor.php /var/www/html/editor.php
RUN chmod 775 /var/www/html/editor.php
COPY chpass.php /var/www/html/chpass.php
RUN chmod 775 /var/www/html/chpass.php
COPY chpass.html /var/www/html/chpass.html
RUN chmod 775 /var/www/html/chpass.html
COPY styles.css /var/www/html/styles.css
RUN chmod 775 /var/www/html/styles.css
RUN rm /var/www/html/index.nginx-debian.html
COPY www.conf /etc/php/8.1/fpm/pool.d/www.conf
EXPOSE 80
CMD /etc/init.d/php8.1-fpm start && nginx -g 'daemon off;'